# permissions for end users to edit buildingblocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildingblock-editor-role
rules:
- apiGroups:
  - simulationworkflow.poc-simulation-workflow.io
  resources:
  - buildingblocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simulationworkflow.poc-simulation-workflow.io
  resources:
  - buildingblocks/status
  verbs:
  - get
