
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - simulationworkflow.poc-simulation-workflow.io
  resources:
  - simulations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simulationworkflow.poc-simulation-workflow.io
  resources:
  - simulations/status
  verbs:
  - get
  - patch
  - update
