# permissions for end users to view simulations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simulation-viewer-role
rules:
- apiGroups:
  - simulationworkflow.poc-simulation-workflow.io
  resources:
  - simulations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simulationworkflow.poc-simulation-workflow.io
  resources:
  - simulations/status
  verbs:
  - get
